name: KaisRandomTeleport
main: net.kaikk.mc.rtp.KaisRandomTP
version: 1.7.1
author: KaiNoMood
softdepend: [WorldBorder]

commands:
   randomtp:
      description: RandomTP main command
      aliases: [rtp,randomteleport]

permissions:
    rtp.use:
        description: Use /rtp 
        default: true
    rtp.bypass:
        description: Permits to bypass time limit
        default: op
 